### ISSUE TITLE
Adding logger 

### ISSUE THREAD

**Issue by webcoderspeed** [koderDev/node.js-programs#6]
hey buddy, I see that your nodejs-programs does not consists any logger. Do I add one? If not then what should I contribute. Can you name any bug/issue

**Comment by koderDev** [comment]
Hmm sure.. you can go for it 👍

**Comment by webcoderspeed** [comment]
bro one question can I install npm packages like winston. or enhance simple console.log

**Comment by koderDev** [comment]
I guess simple console.log will be fine for this repo. 😁

**Comment by webcoderspeed** [comment]
okay bro thanks
